spring.application.name=order-service
server.port=8083

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/orderdb

# URLs của các service khác
# - Dev local: giữ localhost
# - LAN thật:  chạy với profile lan (.\mvnw spring-boot:run -Dspring-boot.run.profiles=lan)
app.user-service.url=http://localhost:8081
app.food-service.url=http://localhost:8082

# CORS - profile local cho phép tất cả
app.cors.allowed-origins=*
