spring:
  application:
    name: food-service
  data:
    mongodb:
      uri: ${DB_MONGODB_URL:mongodb+srv://products:admin@mini-food-system.hbvvgpd.mongodb.net/minifood?retryWrites=true&w=majority&appName=mini-food-system}
server:
  port: 8082
