server:
  port: 8081
  http2:
    enabled: false
  tomcat:
    accept-count: 100

spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: mongodb+srv://products:admin@mini-food-system.hbvvgpd.mongodb.net/minifood?retryWrites=true&w=majority&appName=mini-food-system

jwt:
  secret: ZjQ3MTRkMjgtYjk1MS00ZGE3LTk2MzAtNWU3MjY0MTcyZDBlMTIzNDU2Nzg5MGFiY2RlZg==
  expiration: 86400000
